
name: Auth

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/auth
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - run: npm run eslint:ci
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/auth
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - run: npm run test:ci